### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by 0-BlackSpectrum-0** [Raival-e/File-Explorer-Compose#11]
New v1.10 is not installing on top of v1.0.0 it gives me app conflict!

**Comment by Raival-e** [comment]
I'm sorry for the inconvenience. You would need to uninstall the old version first.

The reason for this conflict is that the latest release uses a different signature. I had to do it to be able to publish it so IzzyDroid.

**Comment by 0-BlackSpectrum-0** [comment]
> I'm sorry for the inconvenience. You would need to uninstall the old version first.
> 
> The reason for this conflict is that the latest release uses a different signature. I had to do it to be able to publish it so IzzyDroid.

Oh OK no problem, future versions after this won't need to uninstall old one right?

**Comment by Raival-e** [comment]
Not after v1.1.1
