### ISSUE TITLE
App is unusable under Android 15

### ISSUE THREAD

**Issue by rusty-snake** [Raival-e/File-Explorer-Compose#15]
App claims to be edge to edge compatible but isn't. App controls are rendered under system ui and can not be interacted with.

OS: GrapheneOS (AOSP 15)
App version: 1.1.1

Edit: issue #15 is about Android 15, lol

**Comment by nekorubu** [comment]
Having the same issue on a Pixel 8 Pro running stock Android 15. Here's what it looks like on my end:
![1000057973](https://github.com/user-attachments/assets/983a2f13-85b0-4f44-b490-ce84f6986b7d)

**Comment by Raival-e** [comment]
Thanks for the feedback!

**Comment by HazyDuck** [comment]
> App claims to be edge to edge compatible but isn't. App controls are rendered under system ui and can not be interacted with.
> 
> OS: GrapheneOS (AOSP 15) App version: 1.1.1
> 
> Edit: issue #15 is about Android 15, lol

I was about to submit the same bug. Thanks. Android 15 latest beta, pixel 8 pro here
