### ISSUE TITLE
Improve UI/UX

### ISSUE THREAD

**Issue by Brajesh3** [Raival-e/File-Explorer-Compose#24]
I didn't know
There is a way to get access to bookmarks
when i was closing the app i saw slider open then i realise
that there exist a way to access bookmarks
![Screenshot_20241106-143633_File Explorer](https://github.com/user-attachments/assets/b1ea85fd-07b0-4f94-833a-be63a19692a7)

**Comment by Raival-e** [comment]
I've received some comments about this behaviour, I'll try to make it more intuitive.

Thanks.
