### ISSUE TITLE
Disappearing files

### ISSUE THREAD

**Issue by Untraveled99** [Raival-e/File-Explorer-Compose#38]
When ever you select a file or folder and click "cut" then go into task and click on that task, the file/folder **disappear**.
No trace of it in hidden files or bin
![Screenshot_20241113-124355_File Explorer](https://github.com/user-attachments/assets/e439548d-75fb-43f7-98e9-67ff7bd6a949)
![Screenshot_20241113-124403_File Explorer](https://github.com/user-attachments/assets/a19fb472-79f8-402a-9355-b79e10ba75dc)

**Comment by Raival-e** [comment]
Thanks for pointing it out, I'll fix it soon.
