### ISSUE TITLE
App crashing when opening PDF.

### ISSUE THREAD

**Issue by egoravsharma** [Raival-e/File-Explorer-Compose#4]
First of all lot of thanks for making the best File Explorer on Android. Built in PDF viewer having an issue while opening PDF. But when we open PDF from 3rd party apps using File Explorer PDF, it works fine.

**Comment by Raival-e** [comment]
You're welcome.

Can you provide more information about the issue you're facing? Does the app crash?

PDF viewer works just fine on my device and the emulator.

**Comment by egoravsharma** [comment]
For more clarity, I saved the same PDF in Internal Storage, External Storage, and WhatsApp. While the PDF in Internal Storage and WhatsApp opened smoothly using File Explorer, the app crashed every time I tried opening the PDF from External Storage.

**Comment by egoravsharma** [comment]
Wait...! It’s not just PDFs—no file is opening from External Storage. Could you try it on your device, in case there's an issue with my SD card?

**Comment by Raival-e** [comment]
There is an issue with opening files from external storage. I'll be looking into it.

Thanks for the details.

**Comment by Raival-e** [comment]
You may now try the [action build](https://github.com/Raival-e/File-Explorer-Compose/actions/runs/11653077407) and see if the problem still occur.
