### ISSUE TITLE
Remember move to recycle bin choice

### ISSUE THREAD

**Issue by hasantahsindagli** [Raival-e/File-Explorer-Compose#47]
Hello,

When I delete a file from the application, instead of deleting it, it moves the files to the directory below. Also, you can't notice it because it doesn't appear in the gallery etc. However, it can be noticed from the space it takes up in the application information section of the phone settings.

(moved files => Android/data/com.raival.compose.file.explorer/files/bin/)

I don't know if this is a bug or something that requires a separate setting.

I'm waiting for a fix or some information.
Thank you, regards.
![Screenshot_2024-12-27-04-20-06-463_com miui securitycenter](https://github.com/user-attachments/assets/6060c905-e94b-42f2-ac72-17178ca4e6df)

**Comment by Raival-e** [comment]
It moves the deleted files to the recycle bin by default, if you don't want that, you can uncheck the checkbox that appears before you delete the files 
![SmartSelect_20241227_074407_File Explorer.jpg](https://github.com/user-attachments/assets/11c64988-87bb-456e-b408-6db4d11687a1)

You can locate the recycle bin directory from new tab dialogue
![SmartSelect_20241227_074433_File Explorer.jpg](https://github.com/user-attachments/assets/4eaefc7b-e337-4fa3-97b6-a183d29772e1)

and then click "empty" from the bottom bar
![SmartSelect_20241227_074538_File Explorer.jpg](https://github.com/user-attachments/assets/ce154f57-68c3-4b80-a15c-e3c14d02228f)

However, I think you're right, I should add an option to remember the choice to that you don't have to uncheck every time you delete something.

**Comment by Raival-e** [comment]
It moves the deleted files to the recycle bin by default, if you don't want that, you can uncheck the checkbox that appears before you delete the files 
![SmartSelect_20241227_074407_File Explorer.jpg](https://github.com/user-attachments/assets/11c64988-87bb-456e-b408-6db4d11687a1)

You can locate the recycle bin directory from new tab dialogue
![SmartSelect_20241227_074433_File Explorer.jpg](https://github.com/user-attachments/assets/4eaefc7b-e337-4fa3-97b6-a183d29772e1)

and then click "empty" from the bottom bar
![SmartSelect_20241227_074538_File Explorer.jpg](https://github.com/user-attachments/assets/ce154f57-68c3-4b80-a15c-e3c14d02228f)

However, I think you're right, I should add an option to remember the choice to that you don't have to uncheck every time you delete something.

**Comment by hasantahsindagli** [comment]
I hadn't noticed that. Thank you for informing me. 
Best regards.

**Comment by hasantahsindagli** [comment]
I hadn't noticed that. Thank you for informing me. 
Best regards.
