### ISSUE TITLE
App Crash when opening file from External Storage

### ISSUE THREAD

**Issue by Yugicchi** [Raival-e/File-Explorer-Compose#6]
### Chronology
The media player works fine in internal storage. I'm able to open txt, pdf, mp3, and mp4 files.

I started to play music in external storage, and the app crashed. I thought it was my music format that isn't supported (m4a and FLAC), so I want to try again using mp3 format, but it keeps crashing.

To strengthen my assumption, I made a file within external storage; at first, it failed to create one. I made another one and it works. Time to open and edit the file, the app crashed.

### Feature implementation request
I noticed that the storage list in the hamburger menu doesn't do much. I can't click any of them. I suppose, whenever we click on the list, a new tab should appear. This will make navigation more natural.

The home button under the tab is also expected to open the home folder where we can see the list of each storage.

**Comment by Raival-e** [comment]
I'd look into it. Thanks for the suggestions.

**Comment by affulito** [comment]
I've experienced this too.

**Comment by Raival-e** [comment]
You may now try the [action build](https://github.com/Raival-e/File-Explorer-Compose/actions/runs/11653077407) and see if the problem still occur.

**Comment by affulito** [comment]
It's working now. Thanks
