### ISSUE TITLE
Word Wrap is inconsistent

### ISSUE THREAD

**Issue by KeronCyst** [Raival-e/File-Explorer-Compose#8]
For whatever reason, Word Wrap in the text editor has only ever actually wrapped once. I've tried it numerous times with .TXT files, opened as homepage shortcuts, opened from the explorer, etc. Ticking the checkbox typically does nothing, and there's no way to make it remember its wrap state.

Samsung S21 FE 5G on Android 12

**Comment by Raival-e** [comment]
Thanks for the comment, I'll look into it.
